---
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [8]
        version_minor_release: [5, 6, 7, 8, 9]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v5

      - name: Test building image
        run: podman build -t docker-oraclelinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }} ./oraclelinux${{ matrix.version_branch }}/. --build-arg VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
      
      - name: Run the built image
        run: podman run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro docker-oraclelinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

      - name: Verify Ansible is accessible in the built image
        run: podman exec --tty test-container env TERM=xterm ansible --version

  tag-release:
    name: Release tags
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [8]
        version_minor_release: [5, 6, 7, 8, 9]

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v5

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./oraclelinux${{ matrix.version_branch }}/.
          platforms: linux/amd64
          push: true
          tags: |
            kirillzak/docker-oraclelinux-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  latest-release:
    name: Latest release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v5

      - name: Add Qemu
        uses: docker/setup-qemu-action@v3

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          build-args: VERSION=8.9
          context: ./oraclelinux8/.
          platforms: linux/amd64
          push: true
          tags: |
            kirillzak/docker-oraclelinux-ansible:latest
            ghcr.io/${{ github.repository }}:latest
